export const districtList = [
  "Bagerhat",
  "Barishal",
  "Bandarban",
  "Barguna",
  "Bhola",
  "Bogura",
  "Brahmanbaria",
  "Chandpur",
  "Chapainawabganj",
  "Chittagong",
  "Chuadanga",
  "Comilla",
  "Cox’s Bazar",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Hobigonj",
  "Jamalpur",
  "Jessore",
  "Jhalokathi",
  "Jhenaida",
  "Joypurhat",
  "Keranigonj",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lalmonirhat",
  "Laxmipur",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Naogaon",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Savar",
  "Shariatpur",
  "Sherpur",
  "Sirajgonj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];
export const productTypes = [
  "Ornaments",
  "Cosmetics",
  "Handicraft",
  "Ceramic",
  "liquid based product",
  "Clothing",
  "Books",
  "Toiletries product",
  "Dry food",
  "Home appliance",
  "Gadget and accessories",
  "Shoes",
  "Picture Frame",
];
